///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAlertArrival = 'assets/images/alert_arrival.png';
  static const String imagesHappyFace = 'assets/images/happy-face.png';
  static const String imagesSleepyFace = 'assets/images/sleepy-face.png';
  static const String imagesWifi = 'assets/images/wifi.png';

}
